name: Build and Test (Python 3.12)
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10,3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Build using Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: install dependancies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install poetry==1.8.3
          poetry install
      #- name: run unitest
      #  run: |
      #    poetry run pytest
